version: "2.4"

services:
  dev_db:
    image: postgres:16
    environment:
      POSTGRES_DB: "example-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "45432:5432"
    volumes:
      - dev_db_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  dev_db_data:
